
export const REQUEST_FORUM_LIST = 'REQUEST_FORUM_LIST';
export const RECEIVE_FORUM_LIST = 'RECEIVE_FORUM_LIST';
export const REJECT_FORUM_LIST = 'REJECT_FORUM_LIST';

export const CHECK_OUT_FORUM = 'CHECK_OUT_FORUM';
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST';
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST';
export const REJECT_ARTICLE_LIST = 'REJECT_ARTICLE_LIST';